### ISSUE TITLE
request.<method> is empty with Django 1.5

### ISSUE THREAD

**Issue by ppo** [croach/django-simple-rest#6]
In Django 1.5, `HttpRequest._load_post_and_files()`:
If content-type doesn't start with "'multipart/form-data'" or "application/x-www-form-urlencoded", an empty QueryDict is set, it no more uses `request.body`.

Django 1.4.5: https://github.com/django/django/blob/1.4.5/django/http/__init__.py#L380
Django 1.5.1: https://github.com/django/django/blob/1.5.1/django/http/request.py#L231

**Comment by jjmontesl** [comment]
Should this issue be closed?

**Comment by ppo** [comment]
I guess it can now.

**Comment by rasheedh** [comment]
Thanks a lot.
